"""add review

Revision ID: ad4e1dfd27a1
Revises: e615f539b685
Create Date: 2025-02-04 15:15:33.921184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4e1dfd27a1'
down_revision = 'e615f539b685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True, foreign_key='customers.id'),
    sa.Column('item_id', sa.Integer(), nullable=True, foreign_key='items.id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
